apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
      version: blue
  template:
    metadata:
      labels:
        app: flask
        version: blue
    spec:
      containers:
        - name: flask-container
          image: supriya334/flask-app:blue-9
          ports:
            - containerPort: 5000
          imagePullPolicy: IfNotPresent
