apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
      version: green
  template:
    metadata:
      labels:
        app: flask
        version: green
      annotations:
        redeploy-timestamp: "{{timestamp}}" # Replace with actual timestamp during deployment
    spec:
      containers:
        - name: flask-container
          image: flask-app:green-31
          ports:
            - containerPort: 5000
          imagePullPolicy: IfNotPresent
