# apiVersion: v1
# kind: Service
# metadata:
#   name: flask-service
# spec:
#   selector:
#     app: flask
#     version: blue # Default to blue; will patch to green when needed
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 5000
#   type: NodePort

apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: LoadBalancer
  selector:
    app: flask
    version: blue
  ports:
    - port: 80
      targetPort: 5000
