apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask
    version: blue  # Will patch to green later
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: NodePort
